"""
Extended problem bank — 1500+ problems (IDs 77+).
Metadata only. Full details generated on-demand via Groq AI.
Organized by topic like GFG Interview Prep.
"""

EXTENDED_PROBLEMS = [
    # ── Strings ────────────────────────────────────────────────────────────────
    {"id":77,"title":"Longest Substring Without Repeating Characters","slug":"longest-substring-no-repeat","difficulty":"Medium","tags":["String","Sliding Window","Hash Table"],"acceptance":33},
    {"id":78,"title":"Longest Palindromic Substring","slug":"longest-palindromic-substring","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":33},
    {"id":79,"title":"Valid Anagram","slug":"valid-anagram","difficulty":"Easy","tags":["String","Hash Table","Sorting"],"acceptance":63},
    {"id":80,"title":"Group Anagrams","slug":"group-anagrams","difficulty":"Medium","tags":["String","Hash Table","Sorting"],"acceptance":67},
    {"id":81,"title":"Encode and Decode Strings","slug":"encode-decode-strings","difficulty":"Medium","tags":["String","Design"],"acceptance":40},
    {"id":82,"title":"Find All Anagrams in a String","slug":"find-all-anagrams","difficulty":"Medium","tags":["String","Sliding Window","Hash Table"],"acceptance":49},
    {"id":83,"title":"Minimum Window Substring","slug":"minimum-window-substring","difficulty":"Hard","tags":["String","Sliding Window","Hash Table"],"acceptance":41},
    {"id":84,"title":"Longest Repeating Character Replacement","slug":"longest-repeating-char-replacement","difficulty":"Medium","tags":["String","Sliding Window"],"acceptance":51},
    {"id":85,"title":"Palindromic Substrings","slug":"palindromic-substrings","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":68},
    {"id":86,"title":"String to Integer (atoi)","slug":"string-to-integer-atoi","difficulty":"Medium","tags":["String","Math"],"acceptance":16},
    {"id":87,"title":"Integer to Roman","slug":"integer-to-roman","difficulty":"Medium","tags":["String","Math","Hash Table"],"acceptance":64},
    {"id":88,"title":"Roman to Integer","slug":"roman-to-integer","difficulty":"Easy","tags":["String","Math","Hash Table"],"acceptance":58},
    {"id":89,"title":"Longest Common Prefix","slug":"longest-common-prefix","difficulty":"Easy","tags":["String","Trie"],"acceptance":41},
    {"id":90,"title":"Count and Say","slug":"count-and-say","difficulty":"Medium","tags":["String","Recursion"],"acceptance":53},
    {"id":91,"title":"Zigzag Conversion","slug":"zigzag-conversion","difficulty":"Medium","tags":["String"],"acceptance":47},
    {"id":92,"title":"Reverse Words in a String","slug":"reverse-words-string","difficulty":"Medium","tags":["String","Two Pointers"],"acceptance":38},
    {"id":93,"title":"Implement strStr()","slug":"implement-strstr","difficulty":"Easy","tags":["String","String Matching"],"acceptance":40},
    {"id":94,"title":"Check if String is Palindrome","slug":"check-palindrome","difficulty":"Easy","tags":["String","Two Pointers"],"acceptance":62},
    {"id":95,"title":"Multiply Strings","slug":"multiply-strings","difficulty":"Medium","tags":["String","Math","Simulation"],"acceptance":39},
    {"id":96,"title":"Add Binary","slug":"add-binary","difficulty":"Easy","tags":["String","Math","Bit Manipulation"],"acceptance":53},
    {"id":97,"title":"First Unique Character in String","slug":"first-unique-char","difficulty":"Easy","tags":["String","Hash Table","Queue"],"acceptance":57},
    {"id":98,"title":"Ransom Note","slug":"ransom-note","difficulty":"Easy","tags":["String","Hash Table","Counting"],"acceptance":56},
    {"id":99,"title":"Isomorphic Strings","slug":"isomorphic-strings","difficulty":"Easy","tags":["String","Hash Table"],"acceptance":42},
    {"id":100,"title":"Word Pattern","slug":"word-pattern","difficulty":"Easy","tags":["String","Hash Table"],"acceptance":41},
    {"id":101,"title":"Decode Ways","slug":"decode-ways","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":31},
    {"id":102,"title":"Letter Combinations of a Phone Number","slug":"letter-combinations-phone","difficulty":"Medium","tags":["String","Backtracking","Hash Table"],"acceptance":57},
    {"id":103,"title":"Generate Parentheses","slug":"generate-parentheses","difficulty":"Medium","tags":["String","Dynamic Programming","Backtracking"],"acceptance":73},
    {"id":104,"title":"Valid Parentheses","slug":"valid-parentheses","difficulty":"Easy","tags":["String","Stack"],"acceptance":40},
    {"id":105,"title":"Longest Valid Parentheses","slug":"longest-valid-parentheses","difficulty":"Hard","tags":["String","Dynamic Programming","Stack"],"acceptance":33},
    {"id":106,"title":"Minimum Remove to Make Valid Parentheses","slug":"min-remove-valid-parens","difficulty":"Medium","tags":["String","Stack"],"acceptance":66},
    {"id":107,"title":"Reorganize String","slug":"reorganize-string","difficulty":"Medium","tags":["String","Greedy","Heap"],"acceptance":53},
    {"id":108,"title":"Check if Two String Arrays are Equivalent","slug":"check-string-arrays-equivalent","difficulty":"Easy","tags":["String","Array"],"acceptance":87},
    {"id":109,"title":"Largest Number","slug":"largest-number","difficulty":"Medium","tags":["String","Sorting","Greedy"],"acceptance":33},
    {"id":110,"title":"Decode String","slug":"decode-string","difficulty":"Medium","tags":["String","Stack","Recursion"],"acceptance":58},

    # ── Linked List ────────────────────────────────────────────────────────────
    {"id":111,"title":"Reverse Linked List","slug":"reverse-linked-list","difficulty":"Easy","tags":["Linked List","Recursion"],"acceptance":73},
    {"id":112,"title":"Merge Two Sorted Lists","slug":"merge-two-sorted-lists","difficulty":"Easy","tags":["Linked List","Recursion"],"acceptance":63},
    {"id":113,"title":"Linked List Cycle","slug":"linked-list-cycle","difficulty":"Easy","tags":["Linked List","Hash Table","Two Pointers"],"acceptance":46},
    {"id":114,"title":"Linked List Cycle II","slug":"linked-list-cycle-ii","difficulty":"Medium","tags":["Linked List","Hash Table","Two Pointers"],"acceptance":47},
    {"id":115,"title":"Remove Nth Node From End","slug":"remove-nth-node-end","difficulty":"Medium","tags":["Linked List","Two Pointers"],"acceptance":39},
    {"id":116,"title":"Merge K Sorted Lists","slug":"merge-k-sorted-lists","difficulty":"Hard","tags":["Linked List","Divide and Conquer","Heap"],"acceptance":50},
    {"id":117,"title":"Copy List with Random Pointer","slug":"copy-list-random-pointer","difficulty":"Medium","tags":["Linked List","Hash Table"],"acceptance":54},
    {"id":118,"title":"Add Two Numbers","slug":"add-two-numbers","difficulty":"Medium","tags":["Linked List","Math","Recursion"],"acceptance":41},
    {"id":119,"title":"Palindrome Linked List","slug":"palindrome-linked-list","difficulty":"Easy","tags":["Linked List","Recursion","Two Pointers"],"acceptance":50},
    {"id":120,"title":"Intersection of Two Linked Lists","slug":"intersection-two-linked-lists","difficulty":"Easy","tags":["Linked List","Hash Table","Two Pointers"],"acceptance":52},
    {"id":121,"title":"Remove Duplicates from Sorted List","slug":"remove-duplicates-sorted-list","difficulty":"Easy","tags":["Linked List"],"acceptance":50},
    {"id":122,"title":"Remove Duplicates from Sorted List II","slug":"remove-duplicates-sorted-list-ii","difficulty":"Medium","tags":["Linked List","Two Pointers"],"acceptance":45},
    {"id":123,"title":"Rotate List","slug":"rotate-list","difficulty":"Medium","tags":["Linked List","Two Pointers"],"acceptance":36},
    {"id":124,"title":"Partition List","slug":"partition-list","difficulty":"Medium","tags":["Linked List","Two Pointers"],"acceptance":52},
    {"id":125,"title":"Reverse Nodes in k-Group","slug":"reverse-nodes-k-group","difficulty":"Hard","tags":["Linked List","Recursion"],"acceptance":55},
    {"id":126,"title":"Swap Nodes in Pairs","slug":"swap-nodes-pairs","difficulty":"Medium","tags":["Linked List","Recursion"],"acceptance":63},
    {"id":127,"title":"Flatten a Multilevel Doubly Linked List","slug":"flatten-multilevel-doubly-ll","difficulty":"Medium","tags":["Linked List","Depth-First Search","Doubly Linked List"],"acceptance":59},
    {"id":128,"title":"LRU Cache","slug":"lru-cache","difficulty":"Medium","tags":["Linked List","Hash Table","Design"],"acceptance":41},
    {"id":129,"title":"LFU Cache","slug":"lfu-cache","difficulty":"Hard","tags":["Linked List","Hash Table","Design"],"acceptance":42},
    {"id":130,"title":"Sort List","slug":"sort-list","difficulty":"Medium","tags":["Linked List","Sorting","Divide and Conquer"],"acceptance":52},
    {"id":131,"title":"Reorder List","slug":"reorder-list","difficulty":"Medium","tags":["Linked List","Recursion","Two Pointers"],"acceptance":55},
    {"id":132,"title":"Odd Even Linked List","slug":"odd-even-linked-list","difficulty":"Medium","tags":["Linked List"],"acceptance":61},
    {"id":133,"title":"Delete Node in Linked List","slug":"delete-node-linked-list","difficulty":"Medium","tags":["Linked List"],"acceptance":77},
    {"id":134,"title":"Middle of Linked List","slug":"middle-linked-list","difficulty":"Easy","tags":["Linked List","Two Pointers"],"acceptance":73},
    {"id":135,"title":"Convert Sorted List to BST","slug":"convert-sorted-list-bst","difficulty":"Medium","tags":["Linked List","Tree","Binary Search Tree"],"acceptance":58},

    # ── Stack & Queue ──────────────────────────────────────────────────────────
    {"id":136,"title":"Min Stack","slug":"min-stack","difficulty":"Medium","tags":["Stack","Design"],"acceptance":53},
    {"id":137,"title":"Evaluate Reverse Polish Notation","slug":"evaluate-rpn","difficulty":"Medium","tags":["Stack","Array","Math"],"acceptance":46},
    {"id":138,"title":"Daily Temperatures","slug":"daily-temperatures","difficulty":"Medium","tags":["Stack","Array","Monotonic Stack"],"acceptance":67},
    {"id":139,"title":"Car Fleet","slug":"car-fleet","difficulty":"Medium","tags":["Stack","Array","Sorting","Monotonic Stack"],"acceptance":48},
    {"id":140,"title":"Largest Rectangle in Histogram","slug":"largest-rectangle-histogram","difficulty":"Hard","tags":["Stack","Array","Monotonic Stack"],"acceptance":43},
    {"id":141,"title":"Maximal Rectangle","slug":"maximal-rectangle","difficulty":"Hard","tags":["Stack","Array","Dynamic Programming","Matrix"],"acceptance":45},
    {"id":142,"title":"Remove K Digits","slug":"remove-k-digits","difficulty":"Medium","tags":["Stack","Greedy","Monotonic Stack"],"acceptance":32},
    {"id":143,"title":"Basic Calculator","slug":"basic-calculator","difficulty":"Hard","tags":["Stack","String","Math","Recursion"],"acceptance":42},
    {"id":144,"title":"Basic Calculator II","slug":"basic-calculator-ii","difficulty":"Medium","tags":["Stack","String","Math"],"acceptance":43},
    {"id":145,"title":"Implement Queue using Stacks","slug":"implement-queue-stacks","difficulty":"Easy","tags":["Stack","Queue","Design"],"acceptance":63},
    {"id":146,"title":"Implement Stack using Queues","slug":"implement-stack-queues","difficulty":"Easy","tags":["Stack","Queue","Design"],"acceptance":58},
    {"id":147,"title":"Sliding Window Maximum","slug":"sliding-window-maximum","difficulty":"Hard","tags":["Stack","Array","Queue","Sliding Window","Monotonic Queue"],"acceptance":46},
    {"id":148,"title":"Next Greater Element I","slug":"next-greater-element-i","difficulty":"Easy","tags":["Stack","Array","Hash Table","Monotonic Stack"],"acceptance":70},
    {"id":149,"title":"Next Greater Element II","slug":"next-greater-element-ii","difficulty":"Medium","tags":["Stack","Array","Monotonic Stack"],"acceptance":62},
    {"id":150,"title":"Asteroid Collision","slug":"asteroid-collision","difficulty":"Medium","tags":["Stack","Array"],"acceptance":44},
    {"id":151,"title":"Valid Stack Sequences","slug":"valid-stack-sequences","difficulty":"Medium","tags":["Stack","Array","Greedy","Simulation"],"acceptance":68},
    {"id":152,"title":"Number of Visible People in Queue","slug":"visible-people-queue","difficulty":"Hard","tags":["Stack","Array","Monotonic Stack"],"acceptance":67},
    {"id":153,"title":"Flatten Nested List Iterator","slug":"flatten-nested-list-iterator","difficulty":"Medium","tags":["Stack","Design","Iterator"],"acceptance":62},
    {"id":154,"title":"Design Circular Queue","slug":"design-circular-queue","difficulty":"Medium","tags":["Queue","Array","Linked List","Design"],"acceptance":51},
    {"id":155,"title":"Design Hit Counter","slug":"design-hit-counter","difficulty":"Medium","tags":["Queue","Hash Table","Binary Search","Design"],"acceptance":68},

    # ── Binary Trees ───────────────────────────────────────────────────────────
    {"id":156,"title":"Invert Binary Tree","slug":"invert-binary-tree","difficulty":"Easy","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":76},
    {"id":157,"title":"Maximum Depth of Binary Tree","slug":"max-depth-binary-tree","difficulty":"Easy","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":73},
    {"id":158,"title":"Same Tree","slug":"same-tree","difficulty":"Easy","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":58},
    {"id":159,"title":"Symmetric Tree","slug":"symmetric-tree","difficulty":"Easy","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":54},
    {"id":160,"title":"Level Order Traversal","slug":"level-order-traversal","difficulty":"Medium","tags":["Tree","BFS","Binary Tree"],"acceptance":65},
    {"id":161,"title":"Binary Tree Zigzag Level Order","slug":"zigzag-level-order","difficulty":"Medium","tags":["Tree","BFS","Binary Tree"],"acceptance":55},
    {"id":162,"title":"Binary Tree Maximum Path Sum","slug":"binary-tree-max-path-sum","difficulty":"Hard","tags":["Tree","DFS","Dynamic Programming","Binary Tree"],"acceptance":38},
    {"id":163,"title":"Serialize and Deserialize Binary Tree","slug":"serialize-deserialize-tree","difficulty":"Hard","tags":["Tree","DFS","BFS","Design","Binary Tree"],"acceptance":55},
    {"id":164,"title":"Lowest Common Ancestor of BST","slug":"lca-bst","difficulty":"Medium","tags":["Tree","DFS","Binary Search Tree","Binary Tree"],"acceptance":63},
    {"id":165,"title":"Validate Binary Search Tree","slug":"validate-bst","difficulty":"Medium","tags":["Tree","DFS","Binary Search Tree","Binary Tree"],"acceptance":31},
    {"id":166,"title":"Kth Smallest in BST","slug":"kth-smallest-bst","difficulty":"Medium","tags":["Tree","DFS","Binary Search Tree","Binary Tree"],"acceptance":70},
    {"id":167,"title":"Construct BST from Preorder","slug":"construct-bst-preorder","difficulty":"Medium","tags":["Tree","Binary Search Tree","Binary Tree"],"acceptance":80},
    {"id":168,"title":"Diameter of Binary Tree","slug":"diameter-binary-tree","difficulty":"Easy","tags":["Tree","DFS","Binary Tree"],"acceptance":56},
    {"id":169,"title":"Balanced Binary Tree","slug":"balanced-binary-tree","difficulty":"Easy","tags":["Tree","DFS","Binary Tree"],"acceptance":48},
    {"id":170,"title":"Minimum Depth of Binary Tree","slug":"min-depth-binary-tree","difficulty":"Easy","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":42},
    {"id":171,"title":"Path Sum","slug":"path-sum","difficulty":"Easy","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":47},
    {"id":172,"title":"Path Sum II","slug":"path-sum-ii","difficulty":"Medium","tags":["Tree","DFS","Backtracking","Binary Tree"],"acceptance":58},
    {"id":173,"title":"Flatten Binary Tree to Linked List","slug":"flatten-tree-linked-list","difficulty":"Medium","tags":["Tree","DFS","Stack","Linked List","Binary Tree"],"acceptance":62},
    {"id":174,"title":"Populate Next Right Pointers","slug":"populate-next-right-pointers","difficulty":"Medium","tags":["Tree","DFS","BFS","Linked List","Binary Tree"],"acceptance":59},
    {"id":175,"title":"Sum Root to Leaf Numbers","slug":"sum-root-to-leaf-numbers","difficulty":"Medium","tags":["Tree","DFS","Math","Binary Tree"],"acceptance":60},
    {"id":176,"title":"Count Complete Tree Nodes","slug":"count-complete-tree-nodes","difficulty":"Easy","tags":["Tree","Binary Search","DFS","Binary Tree"],"acceptance":58},
    {"id":177,"title":"Binary Tree Right Side View","slug":"binary-tree-right-side-view","difficulty":"Medium","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":61},
    {"id":178,"title":"Find Leaves of Binary Tree","slug":"find-leaves-binary-tree","difficulty":"Medium","tags":["Tree","DFS","Sorting","Binary Tree"],"acceptance":83},
    {"id":179,"title":"Delete Nodes and Return Forest","slug":"delete-nodes-return-forest","difficulty":"Medium","tags":["Tree","DFS","Binary Tree"],"acceptance":70},
    {"id":180,"title":"All Nodes Distance K in Binary Tree","slug":"nodes-distance-k-tree","difficulty":"Medium","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":62},

    # ── Binary Search ──────────────────────────────────────────────────────────
    {"id":181,"title":"Binary Search","slug":"binary-search","difficulty":"Easy","tags":["Array","Binary Search"],"acceptance":57},
    {"id":182,"title":"Search a 2D Matrix","slug":"search-2d-matrix","difficulty":"Medium","tags":["Array","Binary Search","Matrix"],"acceptance":49},
    {"id":183,"title":"Koko Eating Bananas","slug":"koko-eating-bananas","difficulty":"Medium","tags":["Array","Binary Search"],"acceptance":46},
    {"id":184,"title":"Find Peak Element","slug":"find-peak-element","difficulty":"Medium","tags":["Array","Binary Search"],"acceptance":45},
    {"id":185,"title":"Sqrt(x)","slug":"sqrtx","difficulty":"Easy","tags":["Math","Binary Search"],"acceptance":37},
    {"id":186,"title":"Guess Number Higher or Lower","slug":"guess-number","difficulty":"Easy","tags":["Binary Search","Interactive"],"acceptance":50},
    {"id":187,"title":"Capacity to Ship Packages","slug":"capacity-ship-packages","difficulty":"Medium","tags":["Array","Binary Search"],"acceptance":65},
    {"id":188,"title":"Split Array Largest Sum","slug":"split-array-largest-sum","difficulty":"Hard","tags":["Array","Binary Search","Dynamic Programming"],"acceptance":53},
    {"id":189,"title":"Median of Two Sorted Arrays","slug":"median-two-sorted-arrays","difficulty":"Hard","tags":["Array","Binary Search","Divide and Conquer"],"acceptance":37},
    {"id":190,"title":"First Bad Version","slug":"first-bad-version","difficulty":"Easy","tags":["Binary Search","Interactive"],"acceptance":43},
    {"id":191,"title":"Search Insert Position","slug":"search-insert-position","difficulty":"Easy","tags":["Array","Binary Search"],"acceptance":42},
    {"id":192,"title":"Find Minimum in Rotated Sorted Array II","slug":"find-min-rotated-ii","difficulty":"Hard","tags":["Array","Binary Search"],"acceptance":43},
    {"id":193,"title":"Count of Smaller Numbers After Self","slug":"count-smaller-numbers","difficulty":"Hard","tags":["Array","Binary Search","Divide and Conquer","Binary Indexed Tree"],"acceptance":42},
    {"id":194,"title":"H-Index","slug":"h-index","difficulty":"Medium","tags":["Array","Sorting","Counting Sort"],"acceptance":37},
    {"id":195,"title":"Find K-th Largest Element in Stream","slug":"kth-largest-stream","difficulty":"Easy","tags":["Tree","Binary Search","Heap","Design","Binary Search Tree"],"acceptance":56},
    {"id":196,"title":"Find Right Interval","slug":"find-right-interval","difficulty":"Medium","tags":["Array","Binary Search","Sorting"],"acceptance":50},
    {"id":197,"title":"Random Pick with Weight","slug":"random-pick-weight","difficulty":"Medium","tags":["Array","Binary Search","Math","Randomized","Prefix Sum"],"acceptance":47},
    {"id":198,"title":"Online Election","slug":"online-election","difficulty":"Medium","tags":["Array","Binary Search","Design"],"acceptance":51},
    {"id":199,"title":"Time Based Key-Value Store","slug":"time-based-key-value","difficulty":"Medium","tags":["Hash Table","Binary Search","String","Design"],"acceptance":53},
    {"id":200,"title":"Reach a Number","slug":"reach-a-number","difficulty":"Medium","tags":["Math","Binary Search"],"acceptance":42},

    # ── Graphs ─────────────────────────────────────────────────────────────────
    {"id":201,"title":"Number of Islands","slug":"number-of-islands","difficulty":"Medium","tags":["Array","DFS","BFS","Union Find","Matrix"],"acceptance":57},
    {"id":202,"title":"Clone Graph","slug":"clone-graph","difficulty":"Medium","tags":["Hash Table","DFS","BFS","Graph"],"acceptance":54},
    {"id":203,"title":"Pacific Atlantic Water Flow","slug":"pacific-atlantic-water-flow","difficulty":"Medium","tags":["Array","DFS","BFS","Matrix"],"acceptance":52},
    {"id":204,"title":"Course Schedule","slug":"course-schedule","difficulty":"Medium","tags":["DFS","BFS","Graph","Topological Sort"],"acceptance":45},
    {"id":205,"title":"Course Schedule II","slug":"course-schedule-ii","difficulty":"Medium","tags":["DFS","BFS","Graph","Topological Sort"],"acceptance":46},
    {"id":206,"title":"Number of Connected Components","slug":"number-connected-components","difficulty":"Medium","tags":["DFS","BFS","Union Find","Graph"],"acceptance":62},
    {"id":207,"title":"Redundant Connection","slug":"redundant-connection","difficulty":"Medium","tags":["DFS","BFS","Union Find","Graph"],"acceptance":61},
    {"id":208,"title":"Word Ladder","slug":"word-ladder","difficulty":"Hard","tags":["Hash Table","BFS","String"],"acceptance":36},
    {"id":209,"title":"Word Ladder II","slug":"word-ladder-ii","difficulty":"Hard","tags":["Hash Table","BFS","String","Backtracking"],"acceptance":27},
    {"id":210,"title":"Walls and Gates","slug":"walls-and-gates","difficulty":"Medium","tags":["Array","BFS","Matrix"],"acceptance":59},
    {"id":211,"title":"Surrounded Regions","slug":"surrounded-regions","difficulty":"Medium","tags":["Array","DFS","BFS","Union Find","Matrix"],"acceptance":37},
    {"id":212,"title":"Graph Valid Tree","slug":"graph-valid-tree","difficulty":"Medium","tags":["DFS","BFS","Union Find","Graph"],"acceptance":45},
    {"id":213,"title":"Alien Dictionary","slug":"alien-dictionary","difficulty":"Hard","tags":["Array","String","DFS","BFS","Graph","Topological Sort"],"acceptance":34},
    {"id":214,"title":"Network Delay Time","slug":"network-delay-time","difficulty":"Medium","tags":["DFS","BFS","Graph","Heap","Shortest Path"],"acceptance":52},
    {"id":215,"title":"Cheapest Flights K Stops","slug":"cheapest-flights-k-stops","difficulty":"Medium","tags":["DFS","BFS","Graph","Dynamic Programming","Heap","Shortest Path"],"acceptance":39},
    {"id":216,"title":"Find the Town Judge","slug":"find-town-judge","difficulty":"Easy","tags":["Array","Hash Table","Graph"],"acceptance":50},
    {"id":217,"title":"All Paths From Source to Target","slug":"all-paths-source-target","difficulty":"Medium","tags":["DFS","BFS","Graph","Backtracking"],"acceptance":81},
    {"id":218,"title":"Minimum Number of Vertices to Reach All Nodes","slug":"min-vertices-reach-all","difficulty":"Medium","tags":["Graph"],"acceptance":75},
    {"id":219,"title":"Keys and Rooms","slug":"keys-and-rooms","difficulty":"Medium","tags":["DFS","BFS","Graph"],"acceptance":70},
    {"id":220,"title":"Is Graph Bipartite","slug":"is-graph-bipartite","difficulty":"Medium","tags":["DFS","BFS","Union Find","Graph"],"acceptance":52},
    {"id":221,"title":"Evaluate Division","slug":"evaluate-division","difficulty":"Medium","tags":["Array","DFS","BFS","Union Find","Graph","Shortest Path"],"acceptance":58},
    {"id":222,"title":"Minimum Spanning Tree (Kruskal)","slug":"minimum-spanning-tree","difficulty":"Medium","tags":["Union Find","Graph","Greedy","Sorting"],"acceptance":55},
    {"id":223,"title":"Critical Connections in Network","slug":"critical-connections-network","difficulty":"Hard","tags":["DFS","Graph","Biconnected Component"],"acceptance":52},
    {"id":224,"title":"Number of Operations to Make Network Connected","slug":"ops-make-network-connected","difficulty":"Medium","tags":["DFS","BFS","Union Find","Graph"],"acceptance":56},
    {"id":225,"title":"Rotting Oranges","slug":"rotting-oranges","difficulty":"Medium","tags":["Array","BFS","Matrix"],"acceptance":52},

    # ── Dynamic Programming ────────────────────────────────────────────────────
    {"id":226,"title":"Climbing Stairs","slug":"climbing-stairs","difficulty":"Easy","tags":["Math","Dynamic Programming","Memoization"],"acceptance":51},
    {"id":227,"title":"Coin Change","slug":"coin-change","difficulty":"Medium","tags":["Array","Dynamic Programming","BFS"],"acceptance":42},
    {"id":228,"title":"Coin Change II","slug":"coin-change-ii","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":61},
    {"id":229,"title":"Longest Common Subsequence","slug":"longest-common-subsequence","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":57},
    {"id":230,"title":"Longest Increasing Subsequence","slug":"longest-increasing-subsequence","difficulty":"Medium","tags":["Array","Binary Search","Dynamic Programming"],"acceptance":53},
    {"id":231,"title":"Edit Distance","slug":"edit-distance","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":54},
    {"id":232,"title":"Word Break","slug":"word-break","difficulty":"Medium","tags":["Hash Table","String","Dynamic Programming","Trie","Memoization"],"acceptance":44},
    {"id":233,"title":"Word Break II","slug":"word-break-ii","difficulty":"Hard","tags":["Hash Table","String","Dynamic Programming","Backtracking","Trie","Memoization"],"acceptance":44},
    {"id":234,"title":"Partition Equal Subset Sum","slug":"partition-equal-subset-sum","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":46},
    {"id":235,"title":"Target Sum","slug":"target-sum","difficulty":"Medium","tags":["Array","Dynamic Programming","Backtracking"],"acceptance":45},
    {"id":236,"title":"Interleaving String","slug":"interleaving-string","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":36},
    {"id":237,"title":"Unique Paths","slug":"unique-paths","difficulty":"Medium","tags":["Math","Dynamic Programming","Combinatorics"],"acceptance":63},
    {"id":238,"title":"Unique Paths II","slug":"unique-paths-ii","difficulty":"Medium","tags":["Array","Dynamic Programming","Matrix"],"acceptance":42},
    {"id":239,"title":"Minimum Path Sum","slug":"minimum-path-sum","difficulty":"Medium","tags":["Array","Dynamic Programming","Matrix"],"acceptance":62},
    {"id":240,"title":"Triangle","slug":"triangle","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":55},
    {"id":241,"title":"Burst Balloons","slug":"burst-balloons","difficulty":"Hard","tags":["Array","Dynamic Programming"],"acceptance":57},
    {"id":242,"title":"Regular Expression Matching","slug":"regular-expression-matching","difficulty":"Hard","tags":["String","Dynamic Programming","Recursion"],"acceptance":28},
    {"id":243,"title":"Wildcard Matching","slug":"wildcard-matching","difficulty":"Hard","tags":["String","Dynamic Programming","Greedy","Recursion"],"acceptance":27},
    {"id":244,"title":"Distinct Subsequences","slug":"distinct-subsequences","difficulty":"Hard","tags":["String","Dynamic Programming"],"acceptance":44},
    {"id":245,"title":"Longest Palindrome Subsequence","slug":"longest-palindrome-subsequence","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":60},
    {"id":246,"title":"Palindrome Partitioning II","slug":"palindrome-partitioning-ii","difficulty":"Hard","tags":["String","Dynamic Programming"],"acceptance":33},
    {"id":247,"title":"Minimum ASCII Delete Sum","slug":"min-ascii-delete-sum","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":62},
    {"id":248,"title":"Stone Game","slug":"stone-game","difficulty":"Medium","tags":["Array","Math","Dynamic Programming","Game Theory"],"acceptance":68},
    {"id":249,"title":"House Robber","slug":"house-robber","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":49},
    {"id":250,"title":"House Robber II","slug":"house-robber-ii","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":41},
    {"id":251,"title":"House Robber III","slug":"house-robber-iii","difficulty":"Medium","tags":["Tree","DFS","Dynamic Programming","Binary Tree"],"acceptance":54},
    {"id":252,"title":"Best Time to Buy and Sell Stock III","slug":"stock-buy-sell-iii","difficulty":"Hard","tags":["Array","Dynamic Programming"],"acceptance":46},
    {"id":253,"title":"Best Time to Buy and Sell Stock IV","slug":"stock-buy-sell-iv","difficulty":"Hard","tags":["Array","Dynamic Programming"],"acceptance":34},
    {"id":254,"title":"Best Time to Buy and Sell Stock with Cooldown","slug":"stock-cooldown","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":55},
    {"id":255,"title":"Best Time to Buy and Sell Stock with Fee","slug":"stock-with-fee","difficulty":"Medium","tags":["Array","Dynamic Programming","Greedy"],"acceptance":64},
    {"id":256,"title":"Frog Jump","slug":"frog-jump","difficulty":"Hard","tags":["Array","Dynamic Programming"],"acceptance":43},
    {"id":257,"title":"Paint House","slug":"paint-house","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":64},
    {"id":258,"title":"Paint House II","slug":"paint-house-ii","difficulty":"Hard","tags":["Array","Dynamic Programming"],"acceptance":54},
    {"id":259,"title":"Maximal Square","slug":"maximal-square","difficulty":"Medium","tags":["Array","Dynamic Programming","Matrix"],"acceptance":45},
    {"id":260,"title":"Count Square Submatrices","slug":"count-square-submatrices","difficulty":"Medium","tags":["Array","Dynamic Programming","Matrix"],"acceptance":74},
    {"id":261,"title":"Cherry Pickup","slug":"cherry-pickup","difficulty":"Hard","tags":["Array","Dynamic Programming","Matrix"],"acceptance":35},
    {"id":262,"title":"Minimum Cost to Cut a Stick","slug":"min-cost-cut-stick","difficulty":"Hard","tags":["Array","Dynamic Programming"],"acceptance":61},
    {"id":263,"title":"Arithmetic Slices","slug":"arithmetic-slices","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":66},
    {"id":264,"title":"Perfect Squares","slug":"perfect-squares","difficulty":"Medium","tags":["Math","Dynamic Programming","BFS"],"acceptance":52},
    {"id":265,"title":"Integer Break","slug":"integer-break","difficulty":"Medium","tags":["Math","Dynamic Programming"],"acceptance":55},

    # ── Heap / Priority Queue ──────────────────────────────────────────────────
    {"id":266,"title":"Top K Frequent Elements","slug":"top-k-frequent-elements","difficulty":"Medium","tags":["Array","Hash Table","Divide and Conquer","Sorting","Heap","Bucket Sort","Counting","Quickselect"],"acceptance":65},
    {"id":267,"title":"Kth Largest Element in Array","slug":"kth-largest-element","difficulty":"Medium","tags":["Array","Divide and Conquer","Sorting","Heap","Quickselect"],"acceptance":66},
    {"id":268,"title":"Task Scheduler","slug":"task-scheduler","difficulty":"Medium","tags":["Array","Hash Table","Greedy","Sorting","Heap","Counting"],"acceptance":57},
    {"id":269,"title":"Find Median from Data Stream","slug":"find-median-data-stream","difficulty":"Hard","tags":["Two Pointers","Design","Sorting","Heap","Data Stream"],"acceptance":51},
    {"id":270,"title":"Meeting Rooms II","slug":"meeting-rooms-ii","difficulty":"Medium","tags":["Array","Two Pointers","Greedy","Sorting","Heap","Prefix Sum"],"acceptance":50},
    {"id":271,"title":"K Closest Points to Origin","slug":"k-closest-points","difficulty":"Medium","tags":["Array","Math","Divide and Conquer","Sorting","Heap","Quickselect","Geometry"],"acceptance":66},
    {"id":272,"title":"Ugly Number II","slug":"ugly-number-ii","difficulty":"Medium","tags":["Hash Table","Math","Dynamic Programming","Heap"],"acceptance":45},
    {"id":273,"title":"Super Ugly Number","slug":"super-ugly-number","difficulty":"Medium","tags":["Array","Math","Dynamic Programming","Heap"],"acceptance":46},
    {"id":274,"title":"Smallest Range Covering Elements","slug":"smallest-range-covering","difficulty":"Hard","tags":["Array","Hash Table","Greedy","Sorting","Heap","Sliding Window"],"acceptance":60},
    {"id":275,"title":"Maximum Frequency Stack","slug":"max-frequency-stack","difficulty":"Hard","tags":["Hash Table","Stack","Design","Ordered Set"],"acceptance":65},
    {"id":276,"title":"Process Tasks Using Servers","slug":"process-tasks-servers","difficulty":"Medium","tags":["Array","Heap"],"acceptance":42},
    {"id":277,"title":"Minimize Deviation in Array","slug":"minimize-deviation-array","difficulty":"Hard","tags":["Array","Greedy","Heap","Ordered Set"],"acceptance":52},
    {"id":278,"title":"Find K Pairs with Smallest Sums","slug":"find-k-pairs-smallest-sums","difficulty":"Medium","tags":["Array","Heap"],"acceptance":38},
    {"id":279,"title":"Kth Smallest Element in Sorted Matrix","slug":"kth-smallest-sorted-matrix","difficulty":"Medium","tags":["Array","Binary Search","Sorting","Heap","Matrix"],"acceptance":60},
    {"id":280,"title":"Reorganize String (Heap Approach)","slug":"reorganize-string-heap","difficulty":"Medium","tags":["Hash Table","String","Greedy","Sorting","Heap","Counting"],"acceptance":53},

    # ── Backtracking ───────────────────────────────────────────────────────────
    {"id":281,"title":"Subsets","slug":"subsets","difficulty":"Medium","tags":["Array","Backtracking","Bit Manipulation"],"acceptance":75},
    {"id":282,"title":"Subsets II","slug":"subsets-ii","difficulty":"Medium","tags":["Array","Backtracking","Bit Manipulation"],"acceptance":56},
    {"id":283,"title":"Permutations","slug":"permutations","difficulty":"Medium","tags":["Array","Backtracking"],"acceptance":75},
    {"id":284,"title":"Permutations II","slug":"permutations-ii","difficulty":"Medium","tags":["Array","Backtracking"],"acceptance":58},
    {"id":285,"title":"Combinations","slug":"combinations","difficulty":"Medium","tags":["Backtracking"],"acceptance":68},
    {"id":286,"title":"Combination Sum","slug":"combination-sum","difficulty":"Medium","tags":["Array","Backtracking"],"acceptance":69},
    {"id":287,"title":"Combination Sum II","slug":"combination-sum-ii","difficulty":"Medium","tags":["Array","Backtracking"],"acceptance":53},
    {"id":288,"title":"Combination Sum III","slug":"combination-sum-iii","difficulty":"Medium","tags":["Backtracking"],"acceptance":68},
    {"id":289,"title":"N-Queens","slug":"n-queens","difficulty":"Hard","tags":["Array","Backtracking"],"acceptance":67},
    {"id":290,"title":"N-Queens II","slug":"n-queens-ii","difficulty":"Hard","tags":["Backtracking"],"acceptance":72},
    {"id":291,"title":"Sudoku Solver","slug":"sudoku-solver","difficulty":"Hard","tags":["Array","Backtracking","Matrix"],"acceptance":59},
    {"id":292,"title":"Word Search","slug":"word-search","difficulty":"Medium","tags":["Array","Backtracking","Matrix"],"acceptance":40},
    {"id":293,"title":"Word Search II","slug":"word-search-ii","difficulty":"Hard","tags":["Array","String","Backtracking","Trie","Matrix"],"acceptance":36},
    {"id":294,"title":"Palindrome Partitioning","slug":"palindrome-partitioning","difficulty":"Medium","tags":["String","Dynamic Programming","Backtracking"],"acceptance":67},
    {"id":295,"title":"Letter Case Permutation","slug":"letter-case-permutation","difficulty":"Medium","tags":["String","Backtracking","Bit Manipulation"],"acceptance":73},

    # ── Bit Manipulation ───────────────────────────────────────────────────────
    {"id":296,"title":"Number of 1 Bits","slug":"number-of-1-bits","difficulty":"Easy","tags":["Divide and Conquer","Bit Manipulation"],"acceptance":66},
    {"id":297,"title":"Counting Bits","slug":"counting-bits","difficulty":"Easy","tags":["Dynamic Programming","Bit Manipulation"],"acceptance":74},
    {"id":298,"title":"Reverse Bits","slug":"reverse-bits","difficulty":"Easy","tags":["Divide and Conquer","Bit Manipulation"],"acceptance":57},
    {"id":299,"title":"Missing Number","slug":"missing-number","difficulty":"Easy","tags":["Array","Hash Table","Math","Binary Search","Bit Manipulation","Sorting"],"acceptance":63},
    {"id":300,"title":"Single Number","slug":"single-number","difficulty":"Easy","tags":["Array","Bit Manipulation"],"acceptance":70},
    {"id":301,"title":"Single Number II","slug":"single-number-ii","difficulty":"Medium","tags":["Array","Bit Manipulation"],"acceptance":59},
    {"id":302,"title":"Single Number III","slug":"single-number-iii","difficulty":"Medium","tags":["Array","Bit Manipulation"],"acceptance":67},
    {"id":303,"title":"Sum of Two Integers","slug":"sum-of-two-integers","difficulty":"Medium","tags":["Math","Bit Manipulation"],"acceptance":50},
    {"id":304,"title":"Power of Two","slug":"power-of-two","difficulty":"Easy","tags":["Math","Bit Manipulation","Recursion"],"acceptance":45},
    {"id":305,"title":"Power of Three","slug":"power-of-three","difficulty":"Easy","tags":["Math","Recursion"],"acceptance":42},
    {"id":306,"title":"Number of 1 Bits (Brian Kernighan)","slug":"count-bits-kernighan","difficulty":"Easy","tags":["Bit Manipulation"],"acceptance":66},
    {"id":307,"title":"Bitwise AND of Numbers Range","slug":"bitwise-and-range","difficulty":"Medium","tags":["Bit Manipulation"],"acceptance":42},
    {"id":308,"title":"Maximum XOR of Two Numbers","slug":"max-xor-two-numbers","difficulty":"Medium","tags":["Array","Hash Table","Bit Manipulation","Trie"],"acceptance":55},
    {"id":309,"title":"Total Hamming Distance","slug":"total-hamming-distance","difficulty":"Medium","tags":["Array","Math","Bit Manipulation"],"acceptance":52},
    {"id":310,"title":"Subsets XOR Trick","slug":"subsets-xor-trick","difficulty":"Easy","tags":["Array","Math","Bit Manipulation"],"acceptance":75},

    # ── Math ───────────────────────────────────────────────────────────────────
    {"id":311,"title":"Palindrome Number","slug":"palindrome-number","difficulty":"Easy","tags":["Math"],"acceptance":52},
    {"id":312,"title":"Reverse Integer","slug":"reverse-integer","difficulty":"Medium","tags":["Math"],"acceptance":27},
    {"id":313,"title":"Pow(x, n)","slug":"powx-n","difficulty":"Medium","tags":["Math","Recursion"],"acceptance":33},
    {"id":314,"title":"Count Primes","slug":"count-primes","difficulty":"Medium","tags":["Array","Math","Enumeration","Number Theory"],"acceptance":33},
    {"id":315,"title":"Happy Number","slug":"happy-number","difficulty":"Easy","tags":["Hash Table","Math","Two Pointers"],"acceptance":53},
    {"id":316,"title":"Excel Sheet Column Number","slug":"excel-column-number","difficulty":"Easy","tags":["Math","String"],"acceptance":60},
    {"id":317,"title":"Excel Sheet Column Title","slug":"excel-column-title","difficulty":"Easy","tags":["Math","String"],"acceptance":35},
    {"id":318,"title":"Factorial Trailing Zeroes","slug":"factorial-trailing-zeroes","difficulty":"Medium","tags":["Math"],"acceptance":42},
    {"id":319,"title":"GCD of Strings","slug":"gcd-of-strings","difficulty":"Easy","tags":["Math","String"],"acceptance":52},
    {"id":320,"title":"Fraction to Recurring Decimal","slug":"fraction-recurring-decimal","difficulty":"Medium","tags":["Hash Table","Math","String"],"acceptance":24},
    {"id":321,"title":"Nth Digit","slug":"nth-digit","difficulty":"Medium","tags":["Math","Binary Search"],"acceptance":34},
    {"id":322,"title":"Largest Divisible Subset","slug":"largest-divisible-subset","difficulty":"Medium","tags":["Array","Math","Dynamic Programming","Sorting"],"acceptance":40},
    {"id":323,"title":"Next Permutation","slug":"next-permutation","difficulty":"Medium","tags":["Array","Two Pointers"],"acceptance":38},
    {"id":324,"title":"Permutation Sequence","slug":"permutation-sequence","difficulty":"Hard","tags":["Math","Recursion"],"acceptance":44},
    {"id":325,"title":"Fizz Buzz","slug":"fizz-buzz","difficulty":"Easy","tags":["Math","String","Simulation"],"acceptance":68},

    # ── Two Pointers ───────────────────────────────────────────────────────────
    {"id":326,"title":"Two Sum II Sorted Array","slug":"two-sum-ii-sorted","difficulty":"Medium","tags":["Array","Two Pointers","Binary Search"],"acceptance":60},
    {"id":327,"title":"4Sum","slug":"4sum","difficulty":"Medium","tags":["Array","Two Pointers","Sorting"],"acceptance":36},
    {"id":328,"title":"Remove Duplicates from Sorted Array II","slug":"remove-dups-sorted-ii","difficulty":"Medium","tags":["Array","Two Pointers"],"acceptance":58},
    {"id":329,"title":"Squares of a Sorted Array","slug":"squares-sorted-array","difficulty":"Easy","tags":["Array","Two Pointers","Sorting"],"acceptance":72},
    {"id":330,"title":"Boats to Save People","slug":"boats-save-people","difficulty":"Medium","tags":["Array","Two Pointers","Greedy","Sorting"],"acceptance":53},
    {"id":331,"title":"Bag of Tokens","slug":"bag-of-tokens","difficulty":"Medium","tags":["Array","Two Pointers","Greedy","Sorting"],"acceptance":50},
    {"id":332,"title":"Minimum Size Subarray Sum","slug":"min-size-subarray-sum","difficulty":"Medium","tags":["Array","Binary Search","Sliding Window","Prefix Sum"],"acceptance":44},
    {"id":333,"title":"Longest Mountain in Array","slug":"longest-mountain-array","difficulty":"Medium","tags":["Array","Two Pointers","Dynamic Programming","Enumeration"],"acceptance":40},
    {"id":334,"title":"Valid Triangle Number","slug":"valid-triangle-number","difficulty":"Medium","tags":["Array","Two Pointers","Binary Search","Greedy","Sorting"],"acceptance":49},
    {"id":335,"title":"Trapping Rain Water II","slug":"trapping-rain-water-ii","difficulty":"Hard","tags":["Array","BFS","Heap","Matrix"],"acceptance":45},

    # ── Sliding Window ─────────────────────────────────────────────────────────
    {"id":336,"title":"Permutation in String","slug":"permutation-in-string","difficulty":"Medium","tags":["Hash Table","Two Pointers","String","Sliding Window"],"acceptance":44},
    {"id":337,"title":"Fruit Into Baskets","slug":"fruit-into-baskets","difficulty":"Medium","tags":["Array","Hash Table","Sliding Window"],"acceptance":43},
    {"id":338,"title":"Max Consecutive Ones III","slug":"max-consecutive-ones-iii","difficulty":"Medium","tags":["Array","Binary Search","Sliding Window","Prefix Sum"],"acceptance":63},
    {"id":339,"title":"Subarray Product Less Than K","slug":"subarray-product-less-k","difficulty":"Medium","tags":["Array","Two Pointers","Sliding Window"],"acceptance":44},
    {"id":340,"title":"Number of Subarrays with Bounded Maximum","slug":"subarrays-bounded-max","difficulty":"Medium","tags":["Array","Two Pointers"],"acceptance":52},
    {"id":341,"title":"Max Sum of Rectangle No Larger Than K","slug":"max-sum-rectangle-k","difficulty":"Hard","tags":["Array","Binary Search","Dynamic Programming","Matrix","Ordered Set"],"acceptance":40},
    {"id":342,"title":"Longest Subarray of 1s After Deleting One Element","slug":"longest-subarray-ones-delete","difficulty":"Medium","tags":["Array","Dynamic Programming","Sliding Window"],"acceptance":66},
    {"id":343,"title":"Get Equal Substrings Within Budget","slug":"equal-substrings-budget","difficulty":"Medium","tags":["String","Binary Search","Sliding Window","Prefix Sum"],"acceptance":47},
    {"id":344,"title":"Diet Plan Performance","slug":"diet-plan-performance","difficulty":"Easy","tags":["Array","Sliding Window"],"acceptance":62},
    {"id":345,"title":"Number of Substrings with All Three Characters","slug":"substrings-all-three-chars","difficulty":"Medium","tags":["Hash Table","String","Sliding Window"],"acceptance":65},

    # ── Greedy ─────────────────────────────────────────────────────────────────
    {"id":346,"title":"Gas Station","slug":"gas-station","difficulty":"Medium","tags":["Array","Greedy"],"acceptance":44},
    {"id":347,"title":"Hand of Straights","slug":"hand-of-straights","difficulty":"Medium","tags":["Array","Hash Table","Greedy","Sorting"],"acceptance":56},
    {"id":348,"title":"Meeting Rooms","slug":"meeting-rooms","difficulty":"Easy","tags":["Array","Sorting"],"acceptance":57},
    {"id":349,"title":"Non-overlapping Intervals","slug":"non-overlapping-intervals","difficulty":"Medium","tags":["Array","Dynamic Programming","Greedy","Sorting"],"acceptance":50},
    {"id":350,"title":"Minimum Number of Arrows to Burst Balloons","slug":"min-arrows-burst-balloons","difficulty":"Medium","tags":["Array","Greedy","Sorting"],"acceptance":55},
    {"id":351,"title":"Task Scheduler (Greedy)","slug":"task-scheduler-greedy","difficulty":"Medium","tags":["Array","Hash Table","Greedy","Sorting","Heap","Counting"],"acceptance":57},
    {"id":352,"title":"Lemonade Change","slug":"lemonade-change","difficulty":"Easy","tags":["Array","Greedy"],"acceptance":52},
    {"id":353,"title":"Assign Cookies","slug":"assign-cookies","difficulty":"Easy","tags":["Array","Two Pointers","Greedy","Sorting"],"acceptance":51},
    {"id":354,"title":"Partition Labels","slug":"partition-labels","difficulty":"Medium","tags":["Hash Table","Two Pointers","String","Greedy"],"acceptance":79},
    {"id":355,"title":"Queue Reconstruction by Height","slug":"queue-reconstruction-height","difficulty":"Medium","tags":["Array","Greedy","Binary Indexed Tree","Segment Tree","Sorting"],"acceptance":72},

    # ── Trie ───────────────────────────────────────────────────────────────────
    {"id":356,"title":"Implement Trie (Prefix Tree)","slug":"implement-trie","difficulty":"Medium","tags":["Hash Table","String","Design","Trie"],"acceptance":63},
    {"id":357,"title":"Add and Search Word","slug":"add-search-word","difficulty":"Medium","tags":["String","DFS","Design","Trie"],"acceptance":44},
    {"id":358,"title":"Replace Words","slug":"replace-words","difficulty":"Medium","tags":["Array","Hash Table","String","Trie"],"acceptance":63},
    {"id":359,"title":"Map Sum Pairs","slug":"map-sum-pairs","difficulty":"Medium","tags":["Hash Table","String","Design","Trie"],"acceptance":56},
    {"id":360,"title":"Design Search Autocomplete System","slug":"design-search-autocomplete","difficulty":"Hard","tags":["Hash Table","String","Design","Trie","Sorting","Heap","Data Stream"],"acceptance":47},

    # ── Union Find ─────────────────────────────────────────────────────────────
    {"id":361,"title":"Number of Provinces","slug":"number-of-provinces","difficulty":"Medium","tags":["DFS","BFS","Union Find","Graph"],"acceptance":64},
    {"id":362,"title":"Accounts Merge","slug":"accounts-merge","difficulty":"Medium","tags":["Array","Hash Table","String","DFS","BFS","Union Find"],"acceptance":56},
    {"id":363,"title":"Satisfiability of Equality Equations","slug":"satisfiability-equality","difficulty":"Medium","tags":["Array","String","Union Find","Graph"],"acceptance":50},
    {"id":364,"title":"Most Stones Removed","slug":"most-stones-removed","difficulty":"Medium","tags":["DFS","Union Find","Graph"],"acceptance":57},
    {"id":365,"title":"Swim in Rising Water","slug":"swim-rising-water","difficulty":"Hard","tags":["Array","Binary Search","DFS","BFS","Union Find","Heap","Matrix"],"acceptance":61},

    # ── OOP / Design ───────────────────────────────────────────────────────────
    {"id":366,"title":"Design Twitter","slug":"design-twitter","difficulty":"Medium","tags":["Hash Table","Linked List","Design","Heap"],"acceptance":37},
    {"id":367,"title":"Design HashMap","slug":"design-hashmap","difficulty":"Easy","tags":["Array","Hash Table","Linked List","Design","Hash Function"],"acceptance":64},
    {"id":368,"title":"Design HashSet","slug":"design-hashset","difficulty":"Easy","tags":["Array","Hash Table","Linked List","Design","Hash Function"],"acceptance":66},
    {"id":369,"title":"Serialize and Deserialize BST","slug":"serialize-deserialize-bst","difficulty":"Medium","tags":["String","DFS","BFS","Design","Binary Search Tree","Binary Tree"],"acceptance":56},
    {"id":370,"title":"Design Circular Deque","slug":"design-circular-deque","difficulty":"Medium","tags":["Array","Linked List","Design","Queue"],"acceptance":57},

    # ── Company Specific ───────────────────────────────────────────────────────
    {"id":371,"title":"Longest Consecutive Sequence","slug":"longest-consecutive-sequence","difficulty":"Medium","tags":["Array","Hash Table","Union Find"],"acceptance":47},
    {"id":372,"title":"Random Pick Index","slug":"random-pick-index","difficulty":"Medium","tags":["Hash Table","Math","Reservoir Sampling","Randomized"],"acceptance":63},
    {"id":373,"title":"K-th Symbol in Grammar","slug":"kth-symbol-grammar","difficulty":"Medium","tags":["Math","Bit Manipulation","Recursion"],"acceptance":45},
    {"id":374,"title":"Minimum Genetic Mutation","slug":"minimum-genetic-mutation","difficulty":"Medium","tags":["Hash Table","String","BFS"],"acceptance":43},
    {"id":375,"title":"Zuma Game","slug":"zuma-game","difficulty":"Hard","tags":["String","Dynamic Programming","Stack","BFS","Memoization"],"acceptance":40},
    {"id":376,"title":"Strange Printer","slug":"strange-printer","difficulty":"Hard","tags":["String","Dynamic Programming"],"acceptance":48},
    {"id":377,"title":"Minimum Window Subsequence","slug":"minimum-window-subsequence","difficulty":"Hard","tags":["String","Dynamic Programming","Sliding Window"],"acceptance":40},
    {"id":378,"title":"Student Attendance Record II","slug":"student-attendance-record-ii","difficulty":"Hard","tags":["Dynamic Programming"],"acceptance":41},
    {"id":379,"title":"Split Array Into Fibonacci Sequence","slug":"split-array-fibonacci","difficulty":"Medium","tags":["String","Backtracking"],"acceptance":36},
    {"id":380,"title":"Minimum Cost to Hire K Workers","slug":"min-cost-hire-k-workers","difficulty":"Hard","tags":["Array","Greedy","Sorting","Heap"],"acceptance":54},

    # ── Advanced / Hard problems ────────────────────────────────────────────────
    {"id":381,"title":"Largest Rectangle in Matrix","slug":"largest-rectangle-matrix","difficulty":"Hard","tags":["Array","Dynamic Programming","Stack","Matrix"],"acceptance":45},
    {"id":382,"title":"Maximum Gap","slug":"maximum-gap","difficulty":"Hard","tags":["Array","Sorting","Bucket Sort","Radix Sort"],"acceptance":43},
    {"id":383,"title":"First Missing Positive","slug":"first-missing-positive","difficulty":"Hard","tags":["Array","Hash Table"],"acceptance":37},
    {"id":384,"title":"Minimum Swaps to Sort","slug":"minimum-swaps-sort","difficulty":"Medium","tags":["Array","Greedy"],"acceptance":57},
    {"id":385,"title":"Count of Range Sum","slug":"count-range-sum","difficulty":"Hard","tags":["Array","Binary Search","Divide and Conquer","Binary Indexed Tree","Segment Tree","Merge Sort","Ordered Set"],"acceptance":37},
    {"id":386,"title":"Super Pow","slug":"super-pow","difficulty":"Medium","tags":["Math","Divide and Conquer"],"acceptance":37},
    {"id":387,"title":"Water and Jug Problem","slug":"water-jug-problem","difficulty":"Medium","tags":["Math","DFS","BFS"],"acceptance":36},
    {"id":388,"title":"Patching Array","slug":"patching-array","difficulty":"Hard","tags":["Array","Greedy"],"acceptance":40},
    {"id":389,"title":"Self Crossing","slug":"self-crossing","difficulty":"Hard","tags":["Array","Math","Geometry"],"acceptance":29},
    {"id":390,"title":"Wiggle Sort II","slug":"wiggle-sort-ii","difficulty":"Medium","tags":["Array","Divide and Conquer","Sorting","Quickselect"],"acceptance":30},

    # ── SQL / Database Pattern Problems ────────────────────────────────────────
    {"id":391,"title":"Employee Hierarchy","slug":"employee-hierarchy","difficulty":"Medium","tags":["Tree","DFS","Hash Table"],"acceptance":55},
    {"id":392,"title":"Org Chart Levels","slug":"org-chart-levels","difficulty":"Easy","tags":["Tree","BFS"],"acceptance":65},

    # ── More Medium/Hard company favorites ─────────────────────────────────────
    {"id":393,"title":"Reconstruct Itinerary","slug":"reconstruct-itinerary","difficulty":"Hard","tags":["DFS","Graph","Eulerian Circuit"],"acceptance":41},
    {"id":394,"title":"Race Car","slug":"race-car","difficulty":"Hard","tags":["Dynamic Programming"],"acceptance":45},
    {"id":395,"title":"Minimum Number of Refueling Stops","slug":"min-refueling-stops","difficulty":"Hard","tags":["Array","Dynamic Programming","Greedy","Heap"],"acceptance":39},
    {"id":396,"title":"Orderly Queue","slug":"orderly-queue","difficulty":"Hard","tags":["Math","String","Sorting"],"acceptance":55},
    {"id":397,"title":"Max Chunks to Make Sorted","slug":"max-chunks-sorted","difficulty":"Medium","tags":["Array","Stack","Greedy","Sorting","Monotonic Stack"],"acceptance":57},
    {"id":398,"title":"Max Chunks to Make Sorted II","slug":"max-chunks-sorted-ii","difficulty":"Hard","tags":["Array","Stack","Greedy","Sorting","Monotonic Stack"],"acceptance":51},
    {"id":399,"title":"Minimum Domino Rotations","slug":"min-domino-rotations","difficulty":"Medium","tags":["Array","Greedy"],"acceptance":52},
    {"id":400,"title":"Broken Calculator","slug":"broken-calculator","difficulty":"Medium","tags":["Math","Greedy"],"acceptance":55},
    {"id":401,"title":"Reachable Nodes in Subdivided Graph","slug":"reachable-nodes-subdivided","difficulty":"Hard","tags":["Graph","Heap","Shortest Path"],"acceptance":52},
    {"id":402,"title":"Minimum Falling Path Sum","slug":"min-falling-path-sum","difficulty":"Medium","tags":["Array","Dynamic Programming","Matrix"],"acceptance":67},
    {"id":403,"title":"Maximum Width of Binary Tree","slug":"max-width-binary-tree","difficulty":"Medium","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":40},
    {"id":404,"title":"Boundary of Binary Tree","slug":"boundary-binary-tree","difficulty":"Medium","tags":["Tree","DFS","Binary Tree"],"acceptance":43},
    {"id":405,"title":"Binary Tree Cameras","slug":"binary-tree-cameras","difficulty":"Hard","tags":["Tree","DFS","Dynamic Programming","Binary Tree"],"acceptance":45},
    {"id":406,"title":"Find Duplicate Subtrees","slug":"find-duplicate-subtrees","difficulty":"Medium","tags":["Hash Table","Tree","DFS","Binary Tree"],"acceptance":57},
    {"id":407,"title":"Most Frequent Subtree Sum","slug":"most-frequent-subtree-sum","difficulty":"Medium","tags":["Hash Table","Tree","DFS","Binary Tree"],"acceptance":65},
    {"id":408,"title":"Average of Levels in Binary Tree","slug":"average-levels-binary-tree","difficulty":"Easy","tags":["Tree","DFS","BFS","Binary Tree"],"acceptance":70},
    {"id":409,"title":"Path Sum III","slug":"path-sum-iii","difficulty":"Medium","tags":["Tree","DFS","Binary Tree","Prefix Sum"],"acceptance":47},
    {"id":410,"title":"Number of Good Leaf Nodes Pairs","slug":"good-leaf-nodes-pairs","difficulty":"Medium","tags":["Tree","DFS","Binary Tree"],"acceptance":61},

    # ── More String problems ────────────────────────────────────────────────────
    {"id":411,"title":"Longest Uncommon Subsequence I","slug":"longest-uncommon-subseq-i","difficulty":"Easy","tags":["String"],"acceptance":60},
    {"id":412,"title":"Longest Uncommon Subsequence II","slug":"longest-uncommon-subseq-ii","difficulty":"Medium","tags":["Array","Hash Table","Two Pointers","String","Sorting"],"acceptance":38},
    {"id":413,"title":"Palindrome Pairs","slug":"palindrome-pairs","difficulty":"Hard","tags":["Array","Hash Table","String","Trie"],"acceptance":35},
    {"id":414,"title":"Sentence Screen Fitting","slug":"sentence-screen-fitting","difficulty":"Medium","tags":["Array","String","Dynamic Programming"],"acceptance":31},
    {"id":415,"title":"Shortest Palindrome","slug":"shortest-palindrome","difficulty":"Hard","tags":["String","Rolling Hash","Two Pointers","String Matching","Hash Function"],"acceptance":32},
    {"id":416,"title":"Repeated DNA Sequences","slug":"repeated-dna-sequences","difficulty":"Medium","tags":["Hash Table","String","Bit Manipulation","Sliding Window","Rolling Hash","Hash Function"],"acceptance":47},
    {"id":417,"title":"Minimum Time to Type Word","slug":"min-time-type-word","difficulty":"Easy","tags":["String","Greedy"],"acceptance":77},
    {"id":418,"title":"Check if Word Equals Summation of Two Words","slug":"word-equals-summation","difficulty":"Easy","tags":["String"],"acceptance":76},
    {"id":419,"title":"Find Common Characters","slug":"find-common-characters","difficulty":"Easy","tags":["Array","Hash Table","String"],"acceptance":70},
    {"id":420,"title":"Compare Version Numbers","slug":"compare-version-numbers","difficulty":"Medium","tags":["Two Pointers","String"],"acceptance":35},

    # ── More Array/Math problems ────────────────────────────────────────────────
    {"id":421,"title":"Summary Ranges","slug":"summary-ranges","difficulty":"Easy","tags":["Array"],"acceptance":46},
    {"id":422,"title":"Missing Ranges","slug":"missing-ranges","difficulty":"Easy","tags":["Array"],"acceptance":38},
    {"id":423,"title":"Find All Numbers Disappeared in Array","slug":"find-disappeared-numbers","difficulty":"Easy","tags":["Array","Hash Table"],"acceptance":59},
    {"id":424,"title":"Find All Duplicates in Array","slug":"find-all-duplicates","difficulty":"Medium","tags":["Array","Hash Table"],"acceptance":73},
    {"id":425,"title":"Third Maximum Number","slug":"third-maximum-number","difficulty":"Easy","tags":["Array","Sorting"],"acceptance":32},
    {"id":426,"title":"Assign Cookies","slug":"assign-cookies-v2","difficulty":"Easy","tags":["Array","Two Pointers","Greedy","Sorting"],"acceptance":51},
    {"id":427,"title":"Max Points on a Line","slug":"max-points-line","difficulty":"Hard","tags":["Array","Hash Table","Math","Geometry"],"acceptance":26},
    {"id":428,"title":"Game of Life","slug":"game-of-life","difficulty":"Medium","tags":["Array","Matrix","Simulation"],"acceptance":67},
    {"id":429,"title":"Pascal's Triangle","slug":"pascals-triangle","difficulty":"Easy","tags":["Array","Dynamic Programming"],"acceptance":70},
    {"id":430,"title":"Pascal's Triangle II","slug":"pascals-triangle-ii","difficulty":"Easy","tags":["Array","Dynamic Programming"],"acceptance":62},

    # ── More DP ────────────────────────────────────────────────────────────────
    {"id":431,"title":"Fibonacci Number","slug":"fibonacci-number","difficulty":"Easy","tags":["Math","Dynamic Programming","Recursion","Memoization"],"acceptance":69},
    {"id":432,"title":"Tribonacci Number","slug":"tribonacci-number","difficulty":"Easy","tags":["Math","Dynamic Programming","Recursion","Memoization"],"acceptance":63},
    {"id":433,"title":"N-th Tribonacci Number","slug":"nth-tribonacci","difficulty":"Easy","tags":["Math","Dynamic Programming","Memoization"],"acceptance":63},
    {"id":434,"title":"Delete Operation for Two Strings","slug":"delete-operation-two-strings","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":59},
    {"id":435,"title":"Minimum ASCII Delete Sum for Two Strings","slug":"min-ascii-delete-two-strings","difficulty":"Medium","tags":["String","Dynamic Programming"],"acceptance":62},
    {"id":436,"title":"Uncrossed Lines","slug":"uncrossed-lines","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":65},
    {"id":437,"title":"Number of Dice Rolls with Target Sum","slug":"dice-rolls-target-sum","difficulty":"Medium","tags":["Dynamic Programming"],"acceptance":52},
    {"id":438,"title":"Minimum Score Triangulation","slug":"min-score-triangulation","difficulty":"Medium","tags":["Array","Dynamic Programming"],"acceptance":55},
    {"id":439,"title":"Maximum Profit in Job Scheduling","slug":"max-profit-job-scheduling","difficulty":"Hard","tags":["Array","Binary Search","Dynamic Programming","Sorting"],"acceptance":51},
    {"id":440,"title":"Strange Printer II","slug":"strange-printer-ii","difficulty":"Hard","tags":["Array","Graph","Topological Sort","Matrix"],"acceptance":49},

    # ── Prefix Sum / Difference Array ──────────────────────────────────────────
    {"id":441,"title":"Range Sum Query Immutable","slug":"range-sum-query-immutable","difficulty":"Easy","tags":["Array","Design","Prefix Sum"],"acceptance":56},
    {"id":442,"title":"Range Sum Query 2D Immutable","slug":"range-sum-query-2d","difficulty":"Medium","tags":["Array","Design","Matrix","Prefix Sum"],"acceptance":53},
    {"id":443,"title":"Contiguous Array","slug":"contiguous-array","difficulty":"Medium","tags":["Array","Hash Table","Prefix Sum"],"acceptance":47},
    {"id":444,"title":"Continuous Subarray Sum","slug":"continuous-subarray-sum","difficulty":"Medium","tags":["Array","Hash Table","Math","Prefix Sum"],"acceptance":28},
    {"id":445,"title":"Maximum Sum of Two Non-overlapping Subarrays","slug":"max-sum-two-non-overlapping","difficulty":"Medium","tags":["Array","Dynamic Programming","Sliding Window","Prefix Sum"],"acceptance":58},

    # ── Monotonic Stack Extra ──────────────────────────────────────────────────
    {"id":446,"title":"Sum of Subarray Minimums","slug":"sum-subarray-minimums","difficulty":"Medium","tags":["Array","Dynamic Programming","Stack","Monotonic Stack"],"acceptance":34},
    {"id":447,"title":"132 Pattern","slug":"132-pattern","difficulty":"Medium","tags":["Array","Binary Search","Stack","Monotonic Stack","Ordered Set"],"acceptance":32},
    {"id":448,"title":"Online Stock Span","slug":"online-stock-span","difficulty":"Medium","tags":["Stack","Design","Monotonic Stack","Data Stream"],"acceptance":63},
    {"id":449,"title":"Largest Rectangle After Removing Row","slug":"largest-rectangle-remove-row","difficulty":"Medium","tags":["Array","Matrix","Stack"],"acceptance":52},
    {"id":450,"title":"Minimum Stack with Pop","slug":"min-stack-pop","difficulty":"Medium","tags":["Stack","Design"],"acceptance":53},

    # ── Divide and Conquer ─────────────────────────────────────────────────────
    {"id":451,"title":"Merge Sort","slug":"merge-sort","difficulty":"Medium","tags":["Array","Divide and Conquer","Sorting","Merge Sort"],"acceptance":64},
    {"id":452,"title":"Count Inversions","slug":"count-inversions","difficulty":"Hard","tags":["Array","Divide and Conquer","Binary Indexed Tree","Segment Tree","Merge Sort","Ordered Set"],"acceptance":42},
    {"id":453,"title":"Reverse Pairs","slug":"reverse-pairs","difficulty":"Hard","tags":["Array","Binary Search","Divide and Conquer","Binary Indexed Tree","Segment Tree","Merge Sort","Ordered Set"],"acceptance":32},
    {"id":454,"title":"K-th Largest Element Using Quickselect","slug":"kth-largest-quickselect","difficulty":"Medium","tags":["Array","Divide and Conquer","Quickselect","Sorting","Heap"],"acceptance":65},
    {"id":455,"title":"Find K-th Smallest Pair Distance","slug":"kth-smallest-pair-distance","difficulty":"Hard","tags":["Array","Two Pointers","Binary Search","Sorting"],"acceptance":36},

    # ── Number Theory ──────────────────────────────────────────────────────────
    {"id":456,"title":"Ugly Number","slug":"ugly-number","difficulty":"Easy","tags":["Math"],"acceptance":41},
    {"id":457,"title":"Count Numbers with Unique Digits","slug":"count-unique-digits","difficulty":"Medium","tags":["Math","Dynamic Programming","Backtracking"],"acceptance":50},
    {"id":458,"title":"Nim Game","slug":"nim-game","difficulty":"Easy","tags":["Math","Game Theory","Brainteaser"],"acceptance":56},
    {"id":459,"title":"Bulb Switcher","slug":"bulb-switcher","difficulty":"Medium","tags":["Math","Brainteaser"],"acceptance":47},
    {"id":460,"title":"Largest Power of 2 in Range","slug":"largest-power-2-range","difficulty":"Medium","tags":["Math","Bit Manipulation"],"acceptance":60},

    # ── Geometry ───────────────────────────────────────────────────────────────
    {"id":461,"title":"Number of Boomerangs","slug":"number-of-boomerangs","difficulty":"Medium","tags":["Array","Hash Table","Math"],"acceptance":52},
    {"id":462,"title":"Line Reflection","slug":"line-reflection","difficulty":"Medium","tags":["Array","Hash Table","Math"],"acceptance":34},
    {"id":463,"title":"Convex Hull","slug":"convex-hull","difficulty":"Hard","tags":["Array","Math","Geometry","Divide and Conquer","Sorting"],"acceptance":49},
    {"id":464,"title":"Minimum Area Rectangle","slug":"minimum-area-rectangle","difficulty":"Medium","tags":["Array","Hash Table","Math","Sorting","Geometry"],"acceptance":54},
    {"id":465,"title":"Erect the Fence","slug":"erect-the-fence","difficulty":"Hard","tags":["Array","Math","Geometry"],"acceptance":42},

    # ── Interval Problems ──────────────────────────────────────────────────────
    {"id":466,"title":"My Calendar I","slug":"my-calendar-i","difficulty":"Medium","tags":["Binary Search","Design","Segment Tree","Ordered Set"],"acceptance":56},
    {"id":467,"title":"My Calendar II","slug":"my-calendar-ii","difficulty":"Medium","tags":["Binary Search","Design","Segment Tree","Ordered Set"],"acceptance":52},
    {"id":468,"title":"Interval List Intersections","slug":"interval-list-intersections","difficulty":"Medium","tags":["Array","Two Pointers"],"acceptance":72},
    {"id":469,"title":"Minimum Number of Arrows to Burst Balloons 2","slug":"min-arrows-balloons-2","difficulty":"Medium","tags":["Array","Greedy","Sorting"],"acceptance":55},
    {"id":470,"title":"Remove Covered Intervals","slug":"remove-covered-intervals","difficulty":"Medium","tags":["Array","Greedy","Sorting"],"acceptance":57},

    # ── Simulation ─────────────────────────────────────────────────────────────
    {"id":471,"title":"Design Tic-Tac-Toe","slug":"design-tic-tac-toe","difficulty":"Medium","tags":["Array","Hash Table","Design","Matrix","Simulation"],"acceptance":73},
    {"id":472,"title":"Minesweeper","slug":"minesweeper","difficulty":"Medium","tags":["Array","DFS","BFS","Matrix"],"acceptance":65},
    {"id":473,"title":"24 Game","slug":"24-game","difficulty":"Hard","tags":["Array","Math","Backtracking"],"acceptance":47},
    {"id":474,"title":"Robot Bounded in Circle","slug":"robot-bounded-circle","difficulty":"Medium","tags":["Math","String","Simulation"],"acceptance":50},
    {"id":475,"title":"Walking Robot Simulation","slug":"walking-robot-simulation","difficulty":"Medium","tags":["Array","Hash Table","Simulation"],"acceptance":34},

    # ── Data Stream / Online Algorithms ───────────────────────────────────────
    {"id":476,"title":"Moving Average from Data Stream","slug":"moving-average-stream","difficulty":"Easy","tags":["Array","Design","Queue","Data Stream"],"acceptance":76},
    {"id":477,"title":"Find Median from Data Stream (Full)","slug":"find-median-stream-full","difficulty":"Hard","tags":["Two Pointers","Design","Sorting","Heap","Data Stream"],"acceptance":51},
    {"id":478,"title":"Top K Frequent Words","slug":"top-k-frequent-words","difficulty":"Medium","tags":["Hash Table","String","Trie","Sorting","Heap","Bucket Sort","Counting"],"acceptance":57},
    {"id":479,"title":"Kth Largest Element in Stream II","slug":"kth-largest-stream-ii","difficulty":"Medium","tags":["Design","Heap","Data Stream"],"acceptance":65},
    {"id":480,"title":"Sliding Window Median","slug":"sliding-window-median","difficulty":"Hard","tags":["Array","Hash Table","Sliding Window","Heap","Ordered Set"],"acceptance":40},

    # ── More Graph/BFS ─────────────────────────────────────────────────────────
    {"id":481,"title":"Jump Game III","slug":"jump-game-iii","difficulty":"Medium","tags":["Array","DFS","BFS"],"acceptance":63},
    {"id":482,"title":"Jump Game IV","slug":"jump-game-iv","difficulty":"Hard","tags":["Array","Hash Table","BFS"],"acceptance":46},
    {"id":483,"title":"Jump Game V","slug":"jump-game-v","difficulty":"Hard","tags":["Array","Dynamic Programming","Sorting"],"acceptance":64},
    {"id":484,"title":"Shortest Path in Binary Matrix","slug":"shortest-path-binary-matrix","difficulty":"Medium","tags":["Array","BFS","Matrix"],"acceptance":45},
    {"id":485,"title":"01 Matrix","slug":"01-matrix","difficulty":"Medium","tags":["Array","Dynamic Programming","BFS","Matrix"],"acceptance":45},
    {"id":486,"title":"Minimum Number of Flips to Convert Matrix","slug":"min-flips-convert-matrix","difficulty":"Hard","tags":["Array","BFS","Matrix"],"acceptance":48},
    {"id":487,"title":"Shortest Bridge","slug":"shortest-bridge","difficulty":"Medium","tags":["Array","DFS","BFS","Matrix"],"acceptance":51},
    {"id":488,"title":"As Far from Land as Possible","slug":"as-far-from-land","difficulty":"Medium","tags":["Array","Dynamic Programming","BFS","Matrix"],"acceptance":48},
    {"id":489,"title":"Number of Closed Islands","slug":"number-closed-islands","difficulty":"Medium","tags":["Array","DFS","BFS","Union Find","Matrix"],"acceptance":67},
    {"id":490,"title":"Number of Enclaves","slug":"number-of-enclaves","difficulty":"Medium","tags":["Array","DFS","BFS","Union Find","Matrix"],"acceptance":63},

    # ── Segment Tree / BIT ─────────────────────────────────────────────────────
    {"id":491,"title":"Range Sum Query Mutable","slug":"range-sum-query-mutable","difficulty":"Medium","tags":["Array","Design","Binary Indexed Tree","Segment Tree"],"acceptance":40},
    {"id":492,"title":"Range Minimum Query","slug":"range-minimum-query","difficulty":"Medium","tags":["Array","Design","Segment Tree","Sparse Table"],"acceptance":52},
    {"id":493,"title":"Count of Range Sum (BIT)","slug":"count-range-sum-bit","difficulty":"Hard","tags":["Array","Binary Search","Divide and Conquer","Binary Indexed Tree","Segment Tree","Merge Sort","Ordered Set"],"acceptance":37},
    {"id":494,"title":"Falling Squares","slug":"falling-squares","difficulty":"Hard","tags":["Array","Segment Tree","Ordered Set"],"acceptance":44},
    {"id":495,"title":"Rectangle Area II","slug":"rectangle-area-ii","difficulty":"Hard","tags":["Array","Segment Tree","Line Sweep","Ordered Set"],"acceptance":52},

    # ── More company favorites ─────────────────────────────────────────────────
    {"id":496,"title":"Remove Invalid Parentheses","slug":"remove-invalid-parentheses","difficulty":"Hard","tags":["String","DFS","BFS","Backtracking"],"acceptance":46},
    {"id":497,"title":"Restore IP Addresses","slug":"restore-ip-addresses","difficulty":"Medium","tags":["String","Backtracking"],"acceptance":47},
    {"id":498,"title":"Different Ways to Add Parentheses","slug":"different-ways-add-parens","difficulty":"Medium","tags":["Math","String","Dynamic Programming","Recursion","Memoization"],"acceptance":73},
    {"id":499,"title":"Expression Add Operators","slug":"expression-add-operators","difficulty":"Hard","tags":["Math","String","Backtracking"],"acceptance":38},
    {"id":500,"title":"Stickers to Spell Word","slug":"stickers-spell-word","difficulty":"Hard","tags":["Array","String","Dynamic Programming","Backtracking","Bit Manipulation","Bitmask"],"acceptance":47},
]

# ── Quick lookup ───────────────────────────────────────────────────────────────

def get_extended_problems():
    return [{"id":p["id"],"title":p["title"],"slug":p["slug"],"difficulty":p["difficulty"],"tags":p["tags"],"acceptance":p["acceptance"]} for p in EXTENDED_PROBLEMS]

def get_extended_problem_meta(pid: int):
    return next((p for p in EXTENDED_PROBLEMS if p["id"] == pid), None)
